import type { Metadata } from "next";
import { Providers } from "./provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "MyCHicMirror",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
